### ISSUE TITLE
wrong answer on this case

### ISSUE THREAD

**Issue by jychan000** [aalmi/HungarianAlgorithm#2]
{3, 6, 6, 5, 0},
{1, 2, 1, 8, 0},
{2, 1, 0, 4, 0},
{1, 9, 5, 9, 0},
{0, 5, 9, 5, 0}

**Comment by rocinant** [comment]
Can I ask what is the main idea under the code, any document explains these squares and marked zeros?

**Comment by aalmi** [comment]
> Can I ask what is the main idea under the code, any document explains these squares and marked zeros?

It's been a couple of years when I wrote this code. I used the German version of the Wikipedia article: https://de.wikipedia.org/wiki/Ungarische_Methode

and http://ccp.uchicago.edu/khetarpal/code/edit-distance/HungarianAlgorithm.java (does not exist anymore)

The marked zeroes are the 0' of the Wikipedia article and the squares are only used as markers: "Draw a square around the element to mark it".... as described in the article.
